// Importing this module registers every core component as a side effect.
export { AuroraButton } from './components/button'
export { AuroraMagnetic } from './components/magnetic'
export { AuroraText } from './components/text'
export { AuroraMarquee } from './components/marquee'
export { AuroraTilt } from './components/tilt'
export { AuroraModal } from './components/modal'
export { AuroraTooltip } from './components/tooltip'
export { AuroraAccordion } from './components/accordion'
export { AuroraTabs, AuroraTabPanel } from './components/tabs'
export { AuroraInput } from './components/input'
export { AuroraSwitch } from './components/switch'
export { AuroraSlider } from './components/slider'
export { AuroraReveal } from './components/reveal'
export { AuroraCounter } from './components/counter'
export { AuroraCursor } from './components/cursor'
export { AuroraNebula } from './components/nebula'
export { AuroraScramble } from './components/scramble'
export { AuroraTypewriter } from './components/typewriter'
export { AuroraLens } from './components/lens'
export { AuroraToaster } from './components/toaster'
export type { ToastOptions } from './components/toaster'
export { AuroraSpotlight } from './components/spotlight'
export { AuroraDock } from './components/dock'
export { AuroraRipple } from './components/ripple'
export { AuroraCarousel } from './components/carousel'
export { AuroraOrbit } from './components/orbit'
export { AuroraGlitch } from './components/glitch'
export { AuroraProgress } from './components/progress'
export { AuroraMenu } from './components/menu'
export { AuroraCompare } from './components/compare'
export { AuroraFlip } from './components/flip'
export { AuroraSkeleton } from './components/skeleton'
export { AuroraConfetti } from './components/confetti'
export type { ConfettiOptions } from './components/confetti'

export { AuroraElement } from './core/base'
export { register } from './core/register'
export { escapeHtml } from './core/html'
export { clamp, lerp, prefersReducedMotion } from './core/motion'
export { whenVisible } from './core/visible'
