// Importing this module registers every core component as a side effect.
export { AuroraButton } from './components/button'
export { AuroraMagnetic } from './components/magnetic'
export { AuroraText } from './components/text'
export { AuroraMarquee } from './components/marquee'
export { AuroraTilt } from './components/tilt'
export { AuroraModal } from './components/modal'
export { AuroraTooltip } from './components/tooltip'
export { AuroraAccordion } from './components/accordion'
export { AuroraTabs, AuroraTabPanel } from './components/tabs'

export { AuroraElement } from './core/base'
export { register } from './core/register'
export { escapeHtml } from './core/html'
export { clamp, lerp, prefersReducedMotion } from './core/motion'
